[package]
name = "mqx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
rumqttd = "0.10.0"
confy = "0.4.0"
pretty_env_logger = "0.4.0"